 define(function(){
	 return {
		 json:[{
				 "title":"西施别恋",
				 "author":"郑源/储兰兰",
				 "imgsrc":"images/music_00.jpg",
				 "music":"audio/music_00.mp3",
				 "time":"05:15"
				 },
				 {
					 "title":"心如刀割",
					 "author":"张学友",
					 "imgsrc":"images/music_01.jpg",
					 "music":"audio/music_01.mp3",
					 "time":"05:04"
				 },
				 {
					 "title":"曾经爱过你",
					 "author":"郑源",
					 "imgsrc":"images/music_02.jpg",
					 "music":"audio/music_02.mp3",
					 "time":"04:19"
				 },
				 {
					 "title":"天池",
					 "author":"李玉刚",
					 "imgsrc":"images/music_03.jpg",
					 "music":"audio/music_03.mp3",
					 "time":"04:00"
				 },
				 {
					 "title":"思思念念全是你",
					 "author":"高安",
					 "imgsrc":"images/music_04.jpg",
					 "music":"audio/music_04.mp3",
					 "time":"04:10"
				 }]
	 };
 });
